# Generated by Django 6.0.7 on 2026-07-23 14:19

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model('marketplace', 'Category')
    categories = ['Phones', 'Laptops', 'Books', 'Clothing', 'Furniture', 'Other']
    for name in categories:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories),
    ]
